name: Retro Stats

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 2 * * *"    # atualiza todo dia às 2h (UTC)
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Verificar e criar package.json
        run: |
          if [ ! -f package.json ]; then
            echo "Criando package.json básico..."
            echo '{
              "name": "retro-stats",
              "version": "1.0.0",
              "description": "Gerador de estatísticas retro",
              "dependencies": {
                "@octokit/rest": "^18.12.0",
                "gifencoder": "^2.0.1",
                "canvas": "^2.9.0"
              }
            }' > package.json
          fi

      - name: Instalar dependências
        run: npm install

      - name: Gerar GIF
        run: node scripts/retro-stats-gif.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commitar arquivo gerado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add retro-stats.gif
          git commit -m "Atualiza retro-stats.gif"
          git push
